ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - core-js
  - esbuild
  - lefthook
  - protobufjs

overrides:
  dompurify@<=3.3.3: '>=3.4.0'
  picomatch@>=4.0.0 <4.0.4: '>=4.0.4'
  protobufjs@<7.5.5: '>=7.5.5'
  vite@>=7.0.0 <=7.3.1: '>=7.3.2'
  vite@>=7.1.0 <=7.3.1: '>=7.3.2'
