ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - core-js
  - esbuild
  - lefthook
  - protobufjs

overrides:
  '@protobufjs/utf8@<1.1.1': '>=1.1.1'
  dompurify@<=3.3.3: '>=3.4.0'
  picomatch@>=4.0.0 <4.0.4: '>=4.0.4'
  postcss@<8.5.10: '>=8.5.10'
  protobufjs@<8.2.0: '>=8.2.0'
  vite@>=7.0.0 <=7.3.1: '>=7.3.2'
  vite@>=7.1.0 <=7.3.1: '>=7.3.2'
  ws@<8.20.1: '>=8.20.1'
